export const DEFAULT_PERMISSIONS = [
  {
    id: 'perm_manage_all',
    action: 'manage',
    subject: 'all',
    description: 'Full system access',
    tenantId: null,
  },
  {
    id: 'perm_create_tenant',
    action: 'create',
    subject: 'tenant',
    description: 'Create organizations',
    tenantId: null,
  },
  {
    id: 'perm_read_tenant',
    action: 'read',
    subject: 'tenant',
    description: 'View organizations',
    tenantId: null,
  },
  {
    id: 'perm_update_tenant',
    action: 'update',
    subject: 'tenant',
    description: 'Update organizations',
    tenantId: null,
  },
  {
    id: 'perm_delete_tenant',
    action: 'delete',
    subject: 'tenant',
    description: 'Delete organizations',
    tenantId: null,
  },
  {
    id: 'perm_manage_user',
    action: 'manage',
    subject: 'user',
    description: 'Manage users',
    tenantId: null,
  },
  {
    id: 'perm_manage_role',
    action: 'manage',
    subject: 'role',
    description: 'Manage roles',
    tenantId: null,
  },
  {
    id: 'perm_manage_permission',
    action: 'manage',
    subject: 'permission',
    description: 'Manage permissions',
    tenantId: null,
  },
  {
    id: 'perm_manage_employee',
    action: 'manage',
    subject: 'employee',
    description: 'Manage employees',
  },
  {
    id: 'perm_read_employee',
    action: 'read',
    subject: 'employee',
    description: 'View employees',
  },
  {
    id: 'perm_manage_department',
    action: 'manage',
    subject: 'department',
    description: 'Manage departments',
  },
  {
    id: 'perm_manage_leave',
    action: 'manage',
    subject: 'leave',
    description: 'Manage leaves',
  },
  {
    id: 'perm_approve_leave',
    action: 'approve',
    subject: 'leave',
    description: 'Approve leave requests',
  },
  {
    id: 'perm_manage_payroll',
    action: 'manage',
    subject: 'payroll',
    description: 'Manage payroll',
  },
  {
    id: 'perm_read_payroll',
    action: 'read',
    subject: 'payroll',
    description: 'View payroll',
  },
  {
    id: 'perm_manage_attendance',
    action: 'manage',
    subject: 'attendance',
    description: 'Manage attendance',
  },
  {
    id: 'perm_read_attendance',
    action: 'read',
    subject: 'attendance',
    description: 'View attendance',
  },
  {
    id: 'perm_manage_attendance_regularization',
    action: 'manage',
    subject: 'attendance_regularization',
    description: 'Manage attendance regularization',
  },
  {
    id: 'perm_approve_attendance_regularization',
    action: 'approve',
    subject: 'attendance_regularization',
    description: 'Approve attendance regularization',
  },
] as const;

